prepare v2.5.2 release, initial pretty changelog
Chatterino/website pull request #617
Opened 2024-12-01 11:34 UTC by pajlada

2024-12-01 14:18 UTC, Mm2PL reviewed
This would be my vision for the changelog:

```
### Added overlay window support
### Improved support for Twitch features //maybe rename this header?
## Moderation //combine these two
    * Added multi-channel support for ban/timeout/untimeout/unban commands,
    * Added support for adding icons to inline moderation actions
### Modified tab visibility control
### Plugins alpha release //remove plugins things from misc features/bugfixes
### User Card Pronouns
### Improved high-DPI support on Windows
### Improved tab unread indicators
### Duplicating tabs
### Updated browser list for "Open links in private mode" feature
### Settings improvements
### Improved link handling
### Helix API emote loading
### Removed beta IRC support // to me this looks like it implies removal of twitch irc but I am not sure how to solve that
### Improved error handling for Twitch API requests
### Miscellaneous features
### Miscellaneous bugfixes
### Nerdier things
```

Also I've spotted a typo

2024-12-01 14:18 UTC, Mm2PL commented on pages/changelog.mdx
> +We now use Twitch's Helix API to load the list of emote's you can post. This means we can now see most emotes you have access to, including event emotes.
Typo in "emote's".
```suggestion
We now use Twitch's Helix API to load the list of emotes you can post. This means we can now see most emotes you have access to, including event emotes.
```

2024-12-08 17:46 UTC, Felanbird requested changes
needs new automod images due to https://github.com/Chatterino/chatterino2/pull/5759

2024-12-08 17:46 UTC, Felanbird commented on pages/changelog.mdx
> +This feature can be enabled with the "Show user's pronouns in user card" setting.
```suggestion
This feature can be enabled with the `Show user's pronouns in user card` setting.
```

2024-12-08 17:46 UTC, Felanbird commented on pages/changelog.mdx
> +- Fixes an issue when double-click selecting outside of a message, multiline-rendering that start at a trailing space, and some RTL text quirks. - Authored by @nerixyz
```suggestion
- Fixes an issue when double-click selecting outside of a message, multiline-rendering that starts at a trailing space, and some RTL text quirks. - Authored by @nerixyz
```
or `started` I guess but I don't really know what this change is

2024-12-08 17:46 UTC, Felanbird commented on pages/changelog.mdx
> +- Fixed tab move animation occasionally failing to start after closing a tab. - Authored by @kornes with help from @nerixyz
```suggestion
- Fixed the animation for moving a tab occasionally failing to display after closing a tab. - Authored by @kornes with help from @nerixyz
```

2024-12-09 22:26 UTC, Wissididom commented on pages/changelog.mdx
> +Have you questions about plugins? Ask in our <a href={discord}>Discord</a> or [start a new
```suggestion
Do you have questions about plugins? Ask in our <a href={discord}>Discord</a> or [start a new
```
This sounded weird to me, so I feel like this should be changed. I've also gathered a "second opinion":
![image](https://github.com/user-attachments/assets/d2b1cb02-98fe-4512-bd80-77d37af9fdbd)

2024-12-09 23:11 UTC, Felanbird commented on pages/changelog.mdx
> +Have you questions about plugins? Ask in our <a href={discord}>Discord</a> or [start a new
could just remove `you` from the original

2024-12-10 09:21 UTC, Nerixyz reviewed
I also have a fix for the header links and their offset in another PR. The header links are a bit weird, because usually, `.`s are replaced by `-` (i.e. `2-5-2`).

2024-12-10 09:21 UTC, Nerixyz commented on pages/changelog.mdx
> +If you were one of the 6 people using the IRC capability of Chatterino2, we have decided to no longer pursue this option - at least not in the way we did here. This release completely removes the IRC
This is subjective. We don't know how many people used IRC - we never deprecated the feature (only a GitHub discussion was opened).

This should read more like "supporting IRC was a burden to maintain and [saw little adoption](https://github.com/Chatterino/chatterino2/discussions/5498)".

2024-12-10 09:21 UTC, Nerixyz commented on pages/changelog.mdx
> +- Improved subscription & resubscriptions messages when they are multi-month subs. - Authored by @iProdigy
```suggestion
- Improved subscription & resubscription messages when they are multi-month subs. - Authored by @iProdigy
```

2024-12-10 09:21 UTC, Nerixyz commented on pages/changelog.mdx
> +- Chatlogs can now be organized by stream IDs rather than the current date. This makes it easier to log streams that consistently cross date boundaries. - Authored by @pajlada
```suggestion
- Chat logs can now be organized by stream IDs rather than the current date. This makes it easier to log streams that consistently cross date boundaries. - Authored by @pajlada
```

2024-12-10 09:21 UTC, Nerixyz commented on pages/changelog.mdx
> +- Shutting down Chatterino2 is now done in a more clean manner, meaning there's less chance for file corruption due to an unclean exit. - Authored by @nerixyz and @pajlada
```suggestion
- Shutting down Chatterino2 is now done in a more clean manner, meaning there's less chance for file corruption due to an unclean exit. If you experience crashes when closing Chatterino, please open an issue. - Authored by @nerixyz and @pajlada
```

2024-12-10 09:21 UTC, Nerixyz commented on pages/changelog.mdx
> +- Fixed incorrect message being disabled in some cases upon approving or denying an automod caught message. - Authored by @iProdigy with help from @jupjohn
```suggestion
- Fixed incorrect message being disabled in some cases upon approving or denying a message caught by AutoMod. - Authored by @iProdigy with help from @jupjohn
```

2024-12-10 09:21 UTC, Nerixyz commented on pages/changelog.mdx
> +overlay window of your selected split.
```suggestion
overlay window of your selected [split](https://wiki.chatterino.com/Glossary/).
```

2024-12-10 09:21 UTC, Nerixyz commented on components/credit.tsx
> +    ]
This will always return the first expression.

2024-12-10 09:21 UTC, Nerixyz commented on components/credit.tsx
> +  // <img src="https://avatars.githubusercontent.com/u/19953266?v=4&amp;s=60" class="gh-avatar">@nerixyz</a> with help from <a href="https://github.com/pajlada" class="gh-author"><img src="https://av
```suggestion
  // <img src="https://avatars.githubusercontent.com/nerixyz?v=4&s=60" class="gh-avatar">@nerixyz</a> with help from <a href="https://github.com/pajlada" class="gh-author"><img src="https://avatars.githubusercontent.com/pajlada?v=4&s=60" class="gh-avatar">@pajlada</a>
```

2024-12-14 10:37 UTC, pajlada commented on pages/changelog.mdx
> +If you were one of the 6 people using the IRC capability of Chatterino2, we have decided to no longer pursue this option - at least not in the way we did here. This release completely removes the IRC
Fixed in [`9cec01f` (#617)](https://github.com/Chatterino/website/pull/617/commits/9cec01f5e9d2c7b4922f3b3715dab3422ba35ee3)

2024-12-14 10:56 UTC, pajlada reviewed
![image](https://github.com/user-attachments/assets/6b9584da-e610-4b91-b824-2b8c4177b21e)

2024-12-14 10:57 UTC, merged